### ISSUE TITLE
Fix: Cannot compile on XCode 12.5.1

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-wallet-mobile#123]
It seems we need to update react-native to support new versions of XCode.

### XCode Errors

Error: `cannot initialize a parameter of type 'NSArray<id<RCTBridgeModule>> *' with an lvalue of type 'NSArray<Class> *__strong' NSArray<RCTModuleData *> *newModules = [self _initializeModules:modules withDispatchGroup:NULL lazilyDiscovered:YES];`
Fix: https://github.com/facebook/react-native/issues/28405#issuecomment-827421253

Error: `/Users/msbrogli/Hathor/hathor-wallet-mobile/node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm:11:9: 'React/RCTAssert.h' file not found`
Fix: Clean build and built it again.

Error: `error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.`
Fix: Run `pod install`, clean build, and build it again.

### Android Studio Errors

Error:
```
> Task :app:mergeReleaseResources FAILED
[drawable-xhdpi-v4/src_assets_images_icerrorbig] /Users/msbrogli/Hathor/hathor-wallet-mobile/android/app/src/main/res/drawable-xhdpi/src_assets_images_icerrorbig.png	[drawable-xhdpi-v4/src_assets_images_icerrorbig] /Users/msbrogli/Hathor/hathor-wallet-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/src_assets_images_icerrorbig.png: Error: Duplicate resources
[drawable-xhdpi-v4/src_assets_icons_chevronleft] /Users/msbrogli/Hathor/hathor-wallet-mobile/android/app/src/main/res/drawable-xhdpi/src_assets_icons_chevronleft.png	[drawable-xhdpi-v4/src_assets_icons_chevronleft] /Users/msbrogli/Hathor/hathor-wallet-mobile/android/app/build/generated/res/react/release/drawable-xhdpi/src_assets_icons_chevronleft.png: Error: Duplicate resources
```
Fix: 

### Acceptance Criteria

- Build on XCode 12.5.1 without any patch.

**Comment by andreabadesso** [comment]
I also had some problems running the app on the simulator using the latest XCode on apple silicon

This is the error I had:
https://github.com/facebook/react-native/issues/26964

"Solved" by replacing `fishhook.c` with the latest one from https://github.com/facebook/fishhook as the latest answer on that issue suggested
