### ISSUE TITLE
[Design] wallet-mobile: new interface for holdings price

### ISSUE THREAD

**Issue by TalisGalhardi** [HathorNetwork/hathor-wallet-mobile#190]
We should define a user-friendly way to display the current price of HTR and any custom tokens that have a public price on the mobile wallet, along with the total value of each holding.

**Comment by TalisGalhardi** [comment]
For this issue, I have put a label right next to the HTR values, as follows:

![image](https://user-images.githubusercontent.com/111133889/188908153-ba607479-f8d1-4ea3-9fcf-2a874bcb515c.png)

@msbrogli and @trondbjoroy please let me know if you have any doubts or suggestions.

**Comment by trondbjoroy** [comment]
I agree with @tuliomir it's not entirely clear in the image. Another option to make it clearer could be to put the $ value below the HTR amount. I.e. it would say 9.98 HTR and right below it ($1.39) or (= $1.39)


I also feel it shouldn't have both the $ sign and USD. Having $ in front of the amount is enough.

**Comment by TalisGalhardi** [comment]
Hello.

What you think about this version?

![image](https://user-images.githubusercontent.com/111133889/189414300-063e3c3f-f128-4557-9b66-518e2f96a3a5.png)

**Comment by trondbjoroy** [comment]
For me, the design is approved now.

**Comment by tuliomir** [comment]
:heavy_check_mark: Approved by me as well: all information is clear.
