### ISSUE TITLE
iOS: Add keys to Info.plist related to encryption export regulations

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-wallet-mobile#226]
Add some keys to `Info.plist` to speed-up the release of new versions. Here is the link to Apple's documentation: https://developer.apple.com/documentation/security/complying_with_encryption_export_regulations

**Comment by andreabadesso** [comment]
This has been addressed in https://github.com/HathorNetwork/hathor-wallet-mobile/pull/225
