### ISSUE TITLE
Pin Screen taking time to confirm Push Notification registration

### ISSUE THREAD

**Issue by alexruzenhack** [HathorNetwork/hathor-wallet-mobile#415]
The Pin Screen takes some time to resume:

https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/dba2bb19-4de9-414c-8f57-b3ee24634d2e

We need to debug this issue either to improve performance or to make it open the loading screen while processing.

Related to https://github.com/HathorNetwork/hathor-wallet-mobile/issues/404

**Comment by tuliomir** [comment]
This behavior similar to one found on android on:
- #369 

Probably refactoring the `PinScreen` to a functional component would help rewrite the exhibition logic, but could have impact on the navigation of other screens.
