### ISSUE TITLE
Duplicate option when validating wallet backup

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet-mobile#59]
A wallet might have a duplicate word among the 24 but, in that case, the options can get duplicated and not be erased.

A minor warning is that the word is used as the react tag key and it can't have a duplicated key. When the same option appears twice we get this warning.

**Duplicated word 'punch'**
![image](https://user-images.githubusercontent.com/3298774/80445383-80a14980-88ea-11ea-942d-72ca03f385e8.png)

**Duplicated option** (normal validation has 5 options, this one has 6 because one 'punch' is never erased)
![image](https://user-images.githubusercontent.com/3298774/80445281-3c15ae00-88ea-11ea-8c28-b8a1a32496a4.png)

**Comment by glevco** [comment]
Fixed on https://github.com/HathorNetwork/hathor-wallet-mobile/pull/234
