### ISSUE TITLE
Easily copy transaction id

### ISSUE THREAD

**Issue by obiyankenobi** [HathorNetwork/hathor-wallet-mobile#80]
When we see the tx details, it'd be nice to be able to copy the id easily. We could add a copy icon or do like the address, just clicking on it.

![image](https://user-images.githubusercontent.com/3236756/87849676-396f9700-c8e2-11ea-9783-22fba3368f7c.png)

**Comment by obiyankenobi** [comment]
Can we close this @pedroferreira1 ?

**Comment by pedroferreira1** [comment]
Yes
